name: Temporary macOS SSH

on:
  push:
    branches:
      - main

jobs:
  mac-temp:
    if: contains(github.event.head_commit.message, 'start')
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          uname -a
          sw_vers
          echo "Arch: $(uname -m)"

      - name: Download latest winload
        run: |
          python3 scripts/download_latest.py
          chmod +x winload
          ./winload --help || true

      - name: Install tmate
        run: |
          brew install tmate

      - name: Start SSH session
        run: |
          echo "Starting SSH session..."
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH COMMAND:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

          echo "Waiting for exit signal..."
          while true; do
            if grep -q "exit mac" ~/.bash_history 2>/dev/null; then
              echo "Exit signal detected."
              break
            fi
            sleep 5
          done